service: pixo

provider:
  name: aws
  runtime: python3.7
  region: ${env:AWS_REGION, 'us-east-1'}

package:
  exclude:
    - venv/**
    - tests/**

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: true

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: api
          method: get

  show:
    handler: handler.show
    events:
      - http:
          path: api/{key}
          method: get

  perform:
    handler: handler.perform
    events:
      - http:
          path: image/{key}
          method: get

plugins:
  - serverless-python-requirements
