service: pixo

provider:
  name: aws
  runtime: python3.7
  region: ${env:AWS_REGION, 'us-east-1'}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  exclude:
    - venv/**
    - tests/**

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: true

functions:
  index:
    name: ${self:service}-api-index
    description: List library images
    handler: handler.index
    events:
      - http:
          path: api
          method: get

  show:
    name: ${self:service}-api-show
    description: Show image specs
    handler: handler.show
    events:
      - http:
          path: api/{key}
          method: get

  perform:
    name: ${self:service}-image
    description: Perform image tags
    handler: handler.perform
    events:
      - http:
          path: image/{key}
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline
